services:

  cinema:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB= ${POSTGRES_DB}
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
