# Generated by Django 4.2.8 on 2023-12-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='market_item',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='order',
        ),
        migrations.DeleteModel(
            name='MarketItem',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
