# Generated by Django 4.2.8 on 2024-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_ordereditem_market_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
