# Generated by Django 4.2.8 on 2024-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_cinema_cinemahall_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='description',
            field=models.CharField(default='Кінотеатр знаходиться: <django.db.models.fields.CharField> Кількість залів:<django.db.models.fields.IntegerField>', max_length=511),
        ),
    ]
