# Generated by Django 4.2.8 on 2024-05-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_cinema_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.CharField(default='Новий кінотеатр', max_length=511),
        ),
    ]
