# Generated by Django 4.2.8 on 2024-05-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_cinema_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
            preserve_default=False,
        ),
    ]
