# Generated by Django 4.2.8 on 2023-12-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_birthday_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
    ]
