# Generated by Django 4.2.8 on 2023-12-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
    ]
