# Generated by Django 4.2.8 on 2023-12-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.CharField(default='0000 0000 0000 0000', max_length=20),
        ),
    ]
