# Generated by Django 4.2.8 on 2023-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.IntegerField(default=0),
        ),
    ]
