# Generated by Django 4.2.8 on 2023-12-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='card',
            new_name='user_card',
        ),
    ]
