# Generated by Django 4.2.8 on 2023-12-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_card_user_user_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_card',
            new_name='card',
        ),
    ]
