# Generated by Django 4.2.8 on 2024-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.IntegerField(default=1111111111111111),
        ),
    ]
